# Generated by Django 3.2.8 on 2021-10-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_audio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='download_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='urls',
            name='length',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urls',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
