# Generated by Django 3.2.8 on 2021-10-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_audio', '0002_auto_20211025_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='VideoInfo',
        ),
    ]
