# Generated by Django 3.2.8 on 2021-10-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_audio', '0003_rename_urls_videoinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='audio',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
