# Generated by Django 3.2.8 on 2021-10-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_audio', '0004_videoinfo_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='audio_type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='video_type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
