# Generated by Django 3.2.8 on 2021-12-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_audio', '0005_auto_20211028_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoinfo',
            old_name='audio_type',
            new_name='abr',
        ),
        migrations.RenameField(
            model_name='videoinfo',
            old_name='video_type',
            new_name='resolution',
        ),
    ]
