# Generated by Django 3.2.8 on 2021-12-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_audio', '0007_auto_20211220_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
